repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
        exclude: LICENSE
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.2
    hooks:
      - id: go-imports-repo
        args:
          - "-local"
          - "github.com/PakaiWA/PakaiWA"
          - "-w"
      - id: go-vet-repo-mod
      - id: go-mod-tidy

  - repo: https://github.com/beeper/pre-commit-go
    rev: v0.4.2
    hooks:
      - id: zerolog-use-stringer

  - repo: local
    hooks:
      - id: gotest
        name: go test (unit tests)
        entry: go test ./...
        language: system
        pass_filenames: false

      # - id: govulncheck
      #   name: govulncheck (Go vulnerability scan)
      #   entry: govulncheck ./...
      #   language: system
      #   pass_filenames: false

      # - id: staticcheck
      #   name: staticcheck (advanced linter)
      #   entry: staticcheck ./...
      #   language: system
      #   pass_filenames: false

      # - id: gosec
      #   name: gosec (security analyzer)
      #   entry: gosec ./...
      #   language: system
      #   pass_filenames: false
